## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'optosigma'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_optosigma become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/NanoQM/pymodaq_plugins_optosigma' 

author = 'Author Name'
author-email = 'Author email'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.3.0', 'pyvisa']

[features]  
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

